#pragma once

void runCubeClassics(uint32_t c, uint8_t mode);
uint8_t findRandomNextSide(uint8_t thisSide);
int effect_z_updown (int iterations, Color col);
int effect_z_updown_move (unsigned char positions[64], unsigned char destinations[64], char axis, Color col);
int draw_positions_axis (char axis, unsigned char positions[64], int invert, Color col);
int stackingRope(int mode, Color col);
int effect_wormsqueeze (int size, int axis, int direction, int iterations, Color col);
int shift (char axis, int direction);
int effect_planboing (int plane, Color col);
void setplane (char axis, unsigned char i, Color col);
void setplane_z (int z, Color col);
void setplane_x (int x, Color col);
void setplane_y (int y, Color col);
int effect_telcstairs (int invert, int val, Color col);
int effect_telcstairs_do(int x, int val, Color col);
int diagonal_planes(Point pA, Point pB, int8_t mode, Color col);
void setCubeVertices(int8_t index);
int folder(uint8_t sideStart, uint8_t sideEnd, Color col);
int effect_axis_updown_randsuspend (char axis, int sleep, int invert, Color col);
int effect_loadbar(int axis, Color col);
int effect_boxside_randsend_parallel (char axis, int origin, int mode, Color col);
int boingboing(uint16_t iterations, unsigned char mode, unsigned char drawmode, Color col);
void flipVoxel(int x, int y, int z, Color newCol);
int ripples (int iterations, Color col);
float sine(float x);
float cosine(float x);
float squareRoot(float x);
float distance2d (float x1, float y1, float x2, float y2);
int linespin (int iterations, char axis, Color col);
int sinelines (int iterations, char axis, Color col);
int spheremove (int iterations, Color col);
float distance3d (float x1, float y1, float z1, float x2, float y2, float z2);
int fireworks (int iterations, int n, Color col);
int effect_rand_patharound (int iterations, Color col);
void font_getpath (unsigned char path, unsigned char *destination, int length);
void effect_pathmove (unsigned char *path, int length);
int zoom_pyramid_clear(Color col);
int zoom_pyramid(Color col);
void box_walls(int x1, int y1, int z1, int x2, int y2, int z2, Color col);
void box_wireframe(int x1, int y1, int z1, int x2, int y2, int z2, Color col);
void argorder(int ix1, int ix2, int *ox1, int *ox2);
